#!/bin/bash

set -e

case "$1" in
    remove)
        echo "Stopping service"
        deb-systemd-helper stop linuxtag.service

        echo "Disabling service"
        deb-systemd-helper disable linuxtag.service

        echo "Removing service"
        rm /usr/lib/systemd/system/linuxtag.service

        echo "Reloading services"
        systemctl daemon-reload
        ;;

    upgrade | deconfigure | failed-upgrade) ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

exit 0
